// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/workload/api/workload.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobStatus int32

const (
	JobStatus_COMPLETED JobStatus = 0
	JobStatus_CANCELLED JobStatus = 1
	JobStatus_FAILED    JobStatus = 2
	JobStatus_UNKNOWN   JobStatus = 3
)

var JobStatus_name = map[int32]string{
	0: "COMPLETED",
	1: "CANCELLED",
	2: "FAILED",
	3: "UNKNOWN",
}

var JobStatus_value = map[string]int32{
	"COMPLETED": 0,
	"CANCELLED": 1,
	"FAILED":    2,
	"UNKNOWN":   3,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}

func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{0}
}

type SubmitJobRequest struct {
	// Bash script that will be submitted to a workload manager.
	Script               string   `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitJobRequest) Reset()         { *m = SubmitJobRequest{} }
func (m *SubmitJobRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitJobRequest) ProtoMessage()    {}
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{0}
}

func (m *SubmitJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitJobRequest.Unmarshal(m, b)
}
func (m *SubmitJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitJobRequest.Marshal(b, m, deterministic)
}
func (m *SubmitJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitJobRequest.Merge(m, src)
}
func (m *SubmitJobRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitJobRequest.Size(m)
}
func (m *SubmitJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitJobRequest proto.InternalMessageInfo

func (m *SubmitJobRequest) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

type SubmitJobResponse struct {
	// Job ID to track submitted job.
	JobId                int64    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitJobResponse) Reset()         { *m = SubmitJobResponse{} }
func (m *SubmitJobResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitJobResponse) ProtoMessage()    {}
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{1}
}

func (m *SubmitJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitJobResponse.Unmarshal(m, b)
}
func (m *SubmitJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitJobResponse.Marshal(b, m, deterministic)
}
func (m *SubmitJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitJobResponse.Merge(m, src)
}
func (m *SubmitJobResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitJobResponse.Size(m)
}
func (m *SubmitJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitJobResponse proto.InternalMessageInfo

func (m *SubmitJobResponse) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type CancelJobRequest struct {
	// ID of a job to be cancelled.
	JobId                int64    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelJobRequest) Reset()         { *m = CancelJobRequest{} }
func (m *CancelJobRequest) String() string { return proto.CompactTextString(m) }
func (*CancelJobRequest) ProtoMessage()    {}
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{2}
}

func (m *CancelJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobRequest.Unmarshal(m, b)
}
func (m *CancelJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobRequest.Marshal(b, m, deterministic)
}
func (m *CancelJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobRequest.Merge(m, src)
}
func (m *CancelJobRequest) XXX_Size() int {
	return xxx_messageInfo_CancelJobRequest.Size(m)
}
func (m *CancelJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobRequest proto.InternalMessageInfo

func (m *CancelJobRequest) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type CancelJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelJobResponse) Reset()         { *m = CancelJobResponse{} }
func (m *CancelJobResponse) String() string { return proto.CompactTextString(m) }
func (*CancelJobResponse) ProtoMessage()    {}
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{3}
}

func (m *CancelJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobResponse.Unmarshal(m, b)
}
func (m *CancelJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobResponse.Marshal(b, m, deterministic)
}
func (m *CancelJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobResponse.Merge(m, src)
}
func (m *CancelJobResponse) XXX_Size() int {
	return xxx_messageInfo_CancelJobResponse.Size(m)
}
func (m *CancelJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobResponse proto.InternalMessageInfo

type JobInfoRequest struct {
	// ID of a job to fetch info of.
	JobId                int64    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobInfoRequest) Reset()         { *m = JobInfoRequest{} }
func (m *JobInfoRequest) String() string { return proto.CompactTextString(m) }
func (*JobInfoRequest) ProtoMessage()    {}
func (*JobInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{4}
}

func (m *JobInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobInfoRequest.Unmarshal(m, b)
}
func (m *JobInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobInfoRequest.Marshal(b, m, deterministic)
}
func (m *JobInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobInfoRequest.Merge(m, src)
}
func (m *JobInfoRequest) XXX_Size() int {
	return xxx_messageInfo_JobInfoRequest.Size(m)
}
func (m *JobInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobInfoRequest proto.InternalMessageInfo

func (m *JobInfoRequest) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type JobInfoResponse struct {
	// Job information.
	Info                 *JobInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobInfoResponse) Reset()         { *m = JobInfoResponse{} }
func (m *JobInfoResponse) String() string { return proto.CompactTextString(m) }
func (*JobInfoResponse) ProtoMessage()    {}
func (*JobInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{5}
}

func (m *JobInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobInfoResponse.Unmarshal(m, b)
}
func (m *JobInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobInfoResponse.Marshal(b, m, deterministic)
}
func (m *JobInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobInfoResponse.Merge(m, src)
}
func (m *JobInfoResponse) XXX_Size() int {
	return xxx_messageInfo_JobInfoResponse.Size(m)
}
func (m *JobInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobInfoResponse proto.InternalMessageInfo

func (m *JobInfoResponse) GetInfo() *JobInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type JobStepsRequest struct {
	// ID of a job to fetch steps of.
	JobId                int64    `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStepsRequest) Reset()         { *m = JobStepsRequest{} }
func (m *JobStepsRequest) String() string { return proto.CompactTextString(m) }
func (*JobStepsRequest) ProtoMessage()    {}
func (*JobStepsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{6}
}

func (m *JobStepsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStepsRequest.Unmarshal(m, b)
}
func (m *JobStepsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStepsRequest.Marshal(b, m, deterministic)
}
func (m *JobStepsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStepsRequest.Merge(m, src)
}
func (m *JobStepsRequest) XXX_Size() int {
	return xxx_messageInfo_JobStepsRequest.Size(m)
}
func (m *JobStepsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStepsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobStepsRequest proto.InternalMessageInfo

func (m *JobStepsRequest) GetJobId() int64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type JobStepsResponse struct {
	// Job steps information.
	JobSteps             []*JobStepInfo `protobuf:"bytes,1,rep,name=job_steps,json=jobSteps,proto3" json:"job_steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *JobStepsResponse) Reset()         { *m = JobStepsResponse{} }
func (m *JobStepsResponse) String() string { return proto.CompactTextString(m) }
func (*JobStepsResponse) ProtoMessage()    {}
func (*JobStepsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{7}
}

func (m *JobStepsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStepsResponse.Unmarshal(m, b)
}
func (m *JobStepsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStepsResponse.Marshal(b, m, deterministic)
}
func (m *JobStepsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStepsResponse.Merge(m, src)
}
func (m *JobStepsResponse) XXX_Size() int {
	return xxx_messageInfo_JobStepsResponse.Size(m)
}
func (m *JobStepsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStepsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobStepsResponse proto.InternalMessageInfo

func (m *JobStepsResponse) GetJobSteps() []*JobStepInfo {
	if m != nil {
		return m.JobSteps
	}
	return nil
}

type OpenFileRequest struct {
	// Path to file to open.
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenFileRequest) Reset()         { *m = OpenFileRequest{} }
func (m *OpenFileRequest) String() string { return proto.CompactTextString(m) }
func (*OpenFileRequest) ProtoMessage()    {}
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{8}
}

func (m *OpenFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenFileRequest.Unmarshal(m, b)
}
func (m *OpenFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenFileRequest.Marshal(b, m, deterministic)
}
func (m *OpenFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenFileRequest.Merge(m, src)
}
func (m *OpenFileRequest) XXX_Size() int {
	return xxx_messageInfo_OpenFileRequest.Size(m)
}
func (m *OpenFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenFileRequest proto.InternalMessageInfo

func (m *OpenFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type TailFileRequest struct {
	// Path to file to tail.
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TailFileRequest) Reset()         { *m = TailFileRequest{} }
func (m *TailFileRequest) String() string { return proto.CompactTextString(m) }
func (*TailFileRequest) ProtoMessage()    {}
func (*TailFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{9}
}

func (m *TailFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TailFileRequest.Unmarshal(m, b)
}
func (m *TailFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TailFileRequest.Marshal(b, m, deterministic)
}
func (m *TailFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TailFileRequest.Merge(m, src)
}
func (m *TailFileRequest) XXX_Size() int {
	return xxx_messageInfo_TailFileRequest.Size(m)
}
func (m *TailFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TailFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TailFileRequest proto.InternalMessageInfo

func (m *TailFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// JobInfo represents compete information about a single job.
type JobInfo struct {
	// ID of a job.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of a user who submitted the job.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Job name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Job exit code. For slurm workload manager will be in form "int:int".
	ExitCode string `protobuf:"bytes,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Job current status.
	Status JobStatus `protobuf:"varint,5,opt,name=status,proto3,enum=api.JobStatus" json:"status,omitempty"`
	// Job submit time.
	SubmitTime *timestamp.Timestamp `protobuf:"bytes,6,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	// Job start time.
	StartTime *timestamp.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Job running time.
	RunTime *duration.Duration `protobuf:"bytes,8,opt,name=run_time,json=runTime,proto3" json:"run_time,omitempty"`
	// Job time limit.
	TimeLimit *duration.Duration `protobuf:"bytes,9,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	// Job working directory.
	WorkingDir string `protobuf:"bytes,10,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// Path to job's standard output file.
	StdOut string `protobuf:"bytes,11,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"`
	// Path to job's standard error file.
	StdErr string `protobuf:"bytes,12,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"`
	// Cluster partition on which job resides.
	Partition string `protobuf:"bytes,13,opt,name=partition,proto3" json:"partition,omitempty"`
	// List of nodes on which job is executed.
	NodeList string `protobuf:"bytes,14,opt,name=node_list,json=nodeList,proto3" json:"node_list,omitempty"`
	// Host from which job was submitted.
	BatchHost string `protobuf:"bytes,15,opt,name=batch_host,json=batchHost,proto3" json:"batch_host,omitempty"`
	// Number of nodes requested by job.
	NumNodes             string   `protobuf:"bytes,16,opt,name=num_nodes,json=numNodes,proto3" json:"num_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobInfo) Reset()         { *m = JobInfo{} }
func (m *JobInfo) String() string { return proto.CompactTextString(m) }
func (*JobInfo) ProtoMessage()    {}
func (*JobInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{10}
}

func (m *JobInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobInfo.Unmarshal(m, b)
}
func (m *JobInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobInfo.Marshal(b, m, deterministic)
}
func (m *JobInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobInfo.Merge(m, src)
}
func (m *JobInfo) XXX_Size() int {
	return xxx_messageInfo_JobInfo.Size(m)
}
func (m *JobInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JobInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JobInfo proto.InternalMessageInfo

func (m *JobInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *JobInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobInfo) GetExitCode() string {
	if m != nil {
		return m.ExitCode
	}
	return ""
}

func (m *JobInfo) GetStatus() JobStatus {
	if m != nil {
		return m.Status
	}
	return JobStatus_COMPLETED
}

func (m *JobInfo) GetSubmitTime() *timestamp.Timestamp {
	if m != nil {
		return m.SubmitTime
	}
	return nil
}

func (m *JobInfo) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *JobInfo) GetRunTime() *duration.Duration {
	if m != nil {
		return m.RunTime
	}
	return nil
}

func (m *JobInfo) GetTimeLimit() *duration.Duration {
	if m != nil {
		return m.TimeLimit
	}
	return nil
}

func (m *JobInfo) GetWorkingDir() string {
	if m != nil {
		return m.WorkingDir
	}
	return ""
}

func (m *JobInfo) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *JobInfo) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

func (m *JobInfo) GetPartition() string {
	if m != nil {
		return m.Partition
	}
	return ""
}

func (m *JobInfo) GetNodeList() string {
	if m != nil {
		return m.NodeList
	}
	return ""
}

func (m *JobInfo) GetBatchHost() string {
	if m != nil {
		return m.BatchHost
	}
	return ""
}

func (m *JobInfo) GetNumNodes() string {
	if m != nil {
		return m.NumNodes
	}
	return ""
}

// JobStepInfo represents information about a single job step.
type JobStepInfo struct {
	// ID od a job step.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Job step name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Job step exit code.
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Job step current status.
	Status JobStatus `protobuf:"varint,4,opt,name=status,proto3,enum=api.JobStatus" json:"status,omitempty"`
	// Job step start time.
	StartTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Job step end time.
	EndTime              *duration.Duration `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *JobStepInfo) Reset()         { *m = JobStepInfo{} }
func (m *JobStepInfo) String() string { return proto.CompactTextString(m) }
func (*JobStepInfo) ProtoMessage()    {}
func (*JobStepInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{11}
}

func (m *JobStepInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStepInfo.Unmarshal(m, b)
}
func (m *JobStepInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStepInfo.Marshal(b, m, deterministic)
}
func (m *JobStepInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStepInfo.Merge(m, src)
}
func (m *JobStepInfo) XXX_Size() int {
	return xxx_messageInfo_JobStepInfo.Size(m)
}
func (m *JobStepInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStepInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JobStepInfo proto.InternalMessageInfo

func (m *JobStepInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobStepInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobStepInfo) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *JobStepInfo) GetStatus() JobStatus {
	if m != nil {
		return m.Status
	}
	return JobStatus_COMPLETED
}

func (m *JobStepInfo) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *JobStepInfo) GetEndTime() *duration.Duration {
	if m != nil {
		return m.EndTime
	}
	return nil
}

// Chunk is an arbitrary amount of bytes.
type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a3bd06263c8633f, []int{12}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.JobStatus", JobStatus_name, JobStatus_value)
	proto.RegisterType((*SubmitJobRequest)(nil), "api.SubmitJobRequest")
	proto.RegisterType((*SubmitJobResponse)(nil), "api.SubmitJobResponse")
	proto.RegisterType((*CancelJobRequest)(nil), "api.CancelJobRequest")
	proto.RegisterType((*CancelJobResponse)(nil), "api.CancelJobResponse")
	proto.RegisterType((*JobInfoRequest)(nil), "api.JobInfoRequest")
	proto.RegisterType((*JobInfoResponse)(nil), "api.JobInfoResponse")
	proto.RegisterType((*JobStepsRequest)(nil), "api.JobStepsRequest")
	proto.RegisterType((*JobStepsResponse)(nil), "api.JobStepsResponse")
	proto.RegisterType((*OpenFileRequest)(nil), "api.OpenFileRequest")
	proto.RegisterType((*TailFileRequest)(nil), "api.TailFileRequest")
	proto.RegisterType((*JobInfo)(nil), "api.JobInfo")
	proto.RegisterType((*JobStepInfo)(nil), "api.JobStepInfo")
	proto.RegisterType((*Chunk)(nil), "api.Chunk")
}

func init() { proto.RegisterFile("pkg/workload/api/workload.proto", fileDescriptor_5a3bd06263c8633f) }

var fileDescriptor_5a3bd06263c8633f = []byte{
	// 787 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xeb, 0x92, 0xdb, 0x34,
	0x18, 0x25, 0xf7, 0xf8, 0xcb, 0x36, 0x71, 0xd5, 0x6e, 0x31, 0xe1, 0xb2, 0xc1, 0x33, 0x40, 0xd8,
	0x19, 0x12, 0x26, 0xed, 0x0c, 0x50, 0x7e, 0x2d, 0x49, 0x3a, 0xa4, 0xa4, 0x09, 0xe3, 0x2e, 0xd3,
	0x9f, 0x1e, 0x39, 0xd6, 0x26, 0xda, 0x4d, 0x24, 0x23, 0xc9, 0x03, 0x2f, 0xc7, 0x7b, 0xf0, 0x06,
	0xbc, 0x06, 0x23, 0x59, 0xce, 0x6d, 0xe9, 0x66, 0xf8, 0x67, 0x9d, 0xef, 0x9c, 0x4f, 0x97, 0xef,
	0xf8, 0xc0, 0x45, 0x72, 0xb7, 0xec, 0xff, 0xc1, 0xc5, 0xdd, 0x9a, 0xe3, 0xb8, 0x8f, 0x13, 0xba,
	0x5d, 0xf4, 0x12, 0xc1, 0x15, 0x47, 0x25, 0x9c, 0xd0, 0xf6, 0xc5, 0x92, 0xf3, 0xe5, 0x9a, 0xf4,
	0x0d, 0x14, 0xa5, 0x37, 0x7d, 0x45, 0x37, 0x44, 0x2a, 0xbc, 0x49, 0x32, 0x56, 0xfb, 0xb3, 0x63,
	0x42, 0x9c, 0x0a, 0xac, 0x28, 0x67, 0x59, 0xdd, 0xbf, 0x04, 0xf7, 0x6d, 0x1a, 0x6d, 0xa8, 0x7a,
	0xcd, 0xa3, 0x80, 0xfc, 0x9e, 0x12, 0xa9, 0xd0, 0x33, 0xa8, 0xca, 0x85, 0xa0, 0x89, 0xf2, 0x0a,
	0x9d, 0x42, 0xd7, 0x09, 0xec, 0xca, 0xbf, 0x84, 0xc7, 0x7b, 0x5c, 0x99, 0x70, 0x26, 0x09, 0x3a,
	0x87, 0xea, 0x2d, 0x8f, 0x42, 0x1a, 0x1b, 0x72, 0x29, 0xa8, 0xdc, 0xf2, 0x68, 0x12, 0xfb, 0x5f,
	0x83, 0x3b, 0xc4, 0x6c, 0x41, 0xd6, 0x7b, 0x7d, 0xdf, 0x43, 0x7d, 0x02, 0x8f, 0xf7, 0xa8, 0x59,
	0x5b, 0xff, 0x2b, 0x68, 0xbe, 0xe6, 0xd1, 0x84, 0xdd, 0xf0, 0x13, 0xea, 0xe7, 0xd0, 0xda, 0x12,
	0xed, 0x91, 0x3a, 0x50, 0xa6, 0xec, 0x86, 0x1b, 0x5e, 0x63, 0x70, 0xd6, 0xc3, 0x09, 0xed, 0xe5,
	0x1c, 0x53, 0xf1, 0xbb, 0x46, 0xf4, 0x56, 0x91, 0x44, 0x9e, 0x68, 0x7f, 0x05, 0xee, 0x8e, 0x69,
	0xfb, 0x7f, 0x03, 0x8e, 0xa6, 0x4a, 0x0d, 0x7a, 0x85, 0x4e, 0xa9, 0xdb, 0x18, 0xb8, 0xf9, 0x26,
	0x9a, 0x69, 0x36, 0xaa, 0xdf, 0x5a, 0x99, 0xff, 0x05, 0xb4, 0xe6, 0x09, 0x61, 0xaf, 0xe8, 0x9a,
	0xe4, 0x9b, 0x21, 0x28, 0x27, 0x58, 0xad, 0xec, 0xfb, 0x9a, 0x6f, 0x4d, 0xbb, 0xc6, 0x74, 0x7d,
	0x8a, 0xf6, 0x57, 0x19, 0x6a, 0xf6, 0x32, 0xa8, 0x09, 0x45, 0x7b, 0x5e, 0x27, 0x28, 0xd2, 0x18,
	0x7d, 0x08, 0xb5, 0x54, 0x12, 0xa1, 0x2f, 0x51, 0xcc, 0x26, 0xa7, 0x97, 0x93, 0x58, 0x37, 0x62,
	0x78, 0x43, 0xbc, 0x52, 0xd6, 0x48, 0x7f, 0xa3, 0x8f, 0xc1, 0x21, 0x7f, 0x52, 0x15, 0x2e, 0x78,
	0x4c, 0xbc, 0xb2, 0x29, 0xd4, 0x35, 0x30, 0xe4, 0x31, 0x41, 0x5f, 0x42, 0x55, 0x2a, 0xac, 0x52,
	0xe9, 0x55, 0x3a, 0x85, 0x6e, 0x73, 0xd0, 0xdc, 0xdd, 0x4f, 0xa3, 0x81, 0xad, 0xa2, 0x1f, 0xa1,
	0x21, 0x8d, 0x25, 0x42, 0x6d, 0x3c, 0xaf, 0x6a, 0x5e, 0xbc, 0xdd, 0xcb, 0x4c, 0xd7, 0xcb, 0x4d,
	0xd7, 0xbb, 0xce, 0x5d, 0x19, 0x40, 0x46, 0xd7, 0x00, 0xfa, 0x01, 0x40, 0x2a, 0x2c, 0xac, 0xb6,
	0x76, 0x52, 0xeb, 0x18, 0xb6, 0x91, 0xbe, 0x80, 0xba, 0x48, 0x59, 0x26, 0xac, 0x1b, 0xe1, 0x47,
	0xf7, 0x84, 0x23, 0xeb, 0xf4, 0xa0, 0x26, 0x52, 0x66, 0x54, 0xdf, 0x03, 0x68, 0x45, 0xb8, 0xa6,
	0x1b, 0xaa, 0x3c, 0xe7, 0x94, 0xce, 0xd1, 0xe4, 0xa9, 0xe6, 0xa2, 0x0b, 0x68, 0xe8, 0xdf, 0x8f,
	0xb2, 0x65, 0x18, 0x53, 0xe1, 0x81, 0x79, 0x2e, 0xb0, 0xd0, 0x88, 0x0a, 0xfd, 0xf4, 0x52, 0xc5,
	0x21, 0x4f, 0x95, 0xd7, 0xb0, 0x3f, 0x8d, 0x8a, 0xe7, 0xa9, 0xca, 0x0b, 0x44, 0x08, 0xef, 0x6c,
	0x5b, 0x18, 0x0b, 0x81, 0x3e, 0x01, 0x27, 0xc1, 0x42, 0x51, 0xbd, 0x95, 0xf7, 0xc8, 0x94, 0x76,
	0x80, 0x9e, 0x0e, 0xe3, 0xb1, 0x3e, 0xaa, 0x54, 0x5e, 0x33, 0x9b, 0x8e, 0x06, 0xa6, 0x54, 0x2a,
	0xf4, 0x29, 0x40, 0x84, 0xd5, 0x62, 0x15, 0xae, 0xb8, 0x54, 0x5e, 0x2b, 0xd3, 0x1a, 0xe4, 0x67,
	0x2e, 0x95, 0xd1, 0xa6, 0x9b, 0x50, 0xd3, 0xa5, 0xe7, 0x5a, 0x6d, 0xba, 0x99, 0xe9, 0xb5, 0xff,
	0x4f, 0x01, 0x1a, 0x7b, 0x3e, 0xbd, 0xe7, 0xa1, 0xdc, 0x2a, 0xc5, 0xf7, 0x59, 0x45, 0x7b, 0xa8,
	0xf2, 0x9f, 0x56, 0x29, 0x3f, 0x68, 0x95, 0xc3, 0x69, 0x57, 0xfe, 0xe7, 0xb4, 0x09, 0x8b, 0xf7,
	0x2d, 0xf6, 0xd0, 0xb4, 0x09, 0x8b, 0xb5, 0xca, 0xff, 0x1c, 0x2a, 0xc3, 0x55, 0xca, 0xee, 0x90,
	0x07, 0xb5, 0x05, 0x67, 0x8a, 0xb0, 0x2c, 0xd0, 0xce, 0x82, 0x7c, 0x79, 0xf9, 0x13, 0x38, 0xdb,
	0x83, 0xa2, 0x47, 0xe0, 0x0c, 0xe7, 0x6f, 0x7e, 0x9d, 0x8e, 0xaf, 0xc7, 0x23, 0xf7, 0x03, 0xb3,
	0xbc, 0x9a, 0x0d, 0xc7, 0xd3, 0xe9, 0x78, 0xe4, 0x16, 0x10, 0x40, 0xf5, 0xd5, 0xd5, 0x44, 0x7f,
	0x17, 0x51, 0x03, 0x6a, 0xbf, 0xcd, 0x7e, 0x99, 0xcd, 0xdf, 0xcd, 0xdc, 0xd2, 0xe0, 0xef, 0x22,
	0xb4, 0xde, 0xd9, 0x68, 0x7e, 0x83, 0x19, 0x5e, 0x12, 0x81, 0x5e, 0x82, 0xb3, 0x4d, 0x4a, 0x74,
	0x6e, 0x1e, 0xe4, 0x38, 0x65, 0xdb, 0xcf, 0x8e, 0x61, 0x9b, 0x2e, 0x2f, 0xc1, 0xd9, 0xc6, 0xa1,
	0xd5, 0x1e, 0x27, 0xa9, 0xd5, 0xde, 0x4b, 0x4d, 0xf4, 0x62, 0x97, 0x0d, 0x4f, 0x0e, 0x62, 0xcf,
	0xea, 0x9e, 0x1e, 0x82, 0x56, 0xf5, 0x1d, 0xd4, 0xf3, 0x8c, 0x43, 0x4f, 0xf7, 0x83, 0x2c, 0x0f,
	0xc7, 0xf6, 0xf9, 0x11, 0x6a, 0x85, 0x3d, 0xa8, 0xe7, 0xc9, 0x66, 0x85, 0x47, 0x41, 0xd7, 0x86,
	0xec, 0xa0, 0x7a, 0x0c, 0xdf, 0x16, 0x34, 0x3f, 0x8f, 0x38, 0xcb, 0x3f, 0x4a, 0xbc, 0x43, 0x7e,
	0x54, 0x35, 0xd3, 0x7d, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xa7, 0x0d, 0xc7, 0x0c,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkloadManagerClient is the client API for WorkloadManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkloadManagerClient interface {
	// SubmitJob submits new job to the workload manager and
	// returns job id that can be used to track job status.
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	// CancelJob cancels job by job id.
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// JobInfo returns complete information about a particular job.
	JobInfo(ctx context.Context, in *JobInfoRequest, opts ...grpc.CallOption) (*JobInfoResponse, error)
	// JobSteps returns information about each individual job step.
	JobSteps(ctx context.Context, in *JobStepsRequest, opts ...grpc.CallOption) (*JobStepsResponse, error)
	// OpenFile opens a file and streams its content back. May be
	// useful for results collecting.
	OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (WorkloadManager_OpenFileClient, error)
	// TailFile opens a file and streams its content back. Unlike
	// OpenFile this call will watch file content changes and stream
	// new chunks continuously.
	TailFile(ctx context.Context, in *TailFileRequest, opts ...grpc.CallOption) (WorkloadManager_TailFileClient, error)
}

type workloadManagerClient struct {
	cc *grpc.ClientConn
}

func NewWorkloadManagerClient(cc *grpc.ClientConn) WorkloadManagerClient {
	return &workloadManagerClient{cc}
}

func (c *workloadManagerClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, "/api.WorkloadManager/SubmitJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadManagerClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, "/api.WorkloadManager/CancelJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadManagerClient) JobInfo(ctx context.Context, in *JobInfoRequest, opts ...grpc.CallOption) (*JobInfoResponse, error) {
	out := new(JobInfoResponse)
	err := c.cc.Invoke(ctx, "/api.WorkloadManager/JobInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadManagerClient) JobSteps(ctx context.Context, in *JobStepsRequest, opts ...grpc.CallOption) (*JobStepsResponse, error) {
	out := new(JobStepsResponse)
	err := c.cc.Invoke(ctx, "/api.WorkloadManager/JobSteps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadManagerClient) OpenFile(ctx context.Context, in *OpenFileRequest, opts ...grpc.CallOption) (WorkloadManager_OpenFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WorkloadManager_serviceDesc.Streams[0], "/api.WorkloadManager/OpenFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &workloadManagerOpenFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkloadManager_OpenFileClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type workloadManagerOpenFileClient struct {
	grpc.ClientStream
}

func (x *workloadManagerOpenFileClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workloadManagerClient) TailFile(ctx context.Context, in *TailFileRequest, opts ...grpc.CallOption) (WorkloadManager_TailFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WorkloadManager_serviceDesc.Streams[1], "/api.WorkloadManager/TailFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &workloadManagerTailFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkloadManager_TailFileClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type workloadManagerTailFileClient struct {
	grpc.ClientStream
}

func (x *workloadManagerTailFileClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorkloadManagerServer is the server API for WorkloadManager service.
type WorkloadManagerServer interface {
	// SubmitJob submits new job to the workload manager and
	// returns job id that can be used to track job status.
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	// CancelJob cancels job by job id.
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// JobInfo returns complete information about a particular job.
	JobInfo(context.Context, *JobInfoRequest) (*JobInfoResponse, error)
	// JobSteps returns information about each individual job step.
	JobSteps(context.Context, *JobStepsRequest) (*JobStepsResponse, error)
	// OpenFile opens a file and streams its content back. May be
	// useful for results collecting.
	OpenFile(*OpenFileRequest, WorkloadManager_OpenFileServer) error
	// TailFile opens a file and streams its content back. Unlike
	// OpenFile this call will watch file content changes and stream
	// new chunks continuously.
	TailFile(*TailFileRequest, WorkloadManager_TailFileServer) error
}

// UnimplementedWorkloadManagerServer can be embedded to have forward compatible implementations.
type UnimplementedWorkloadManagerServer struct {
}

func (*UnimplementedWorkloadManagerServer) SubmitJob(ctx context.Context, req *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}
func (*UnimplementedWorkloadManagerServer) CancelJob(ctx context.Context, req *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (*UnimplementedWorkloadManagerServer) JobInfo(ctx context.Context, req *JobInfoRequest) (*JobInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobInfo not implemented")
}
func (*UnimplementedWorkloadManagerServer) JobSteps(ctx context.Context, req *JobStepsRequest) (*JobStepsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobSteps not implemented")
}
func (*UnimplementedWorkloadManagerServer) OpenFile(req *OpenFileRequest, srv WorkloadManager_OpenFileServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenFile not implemented")
}
func (*UnimplementedWorkloadManagerServer) TailFile(req *TailFileRequest, srv WorkloadManager_TailFileServer) error {
	return status.Errorf(codes.Unimplemented, "method TailFile not implemented")
}

func RegisterWorkloadManagerServer(s *grpc.Server, srv WorkloadManagerServer) {
	s.RegisterService(&_WorkloadManager_serviceDesc, srv)
}

func _WorkloadManager_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadManagerServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkloadManager/SubmitJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadManagerServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadManager_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadManagerServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkloadManager/CancelJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadManagerServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadManager_JobInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadManagerServer).JobInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkloadManager/JobInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadManagerServer).JobInfo(ctx, req.(*JobInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadManager_JobSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadManagerServer).JobSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WorkloadManager/JobSteps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadManagerServer).JobSteps(ctx, req.(*JobStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadManager_OpenFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkloadManagerServer).OpenFile(m, &workloadManagerOpenFileServer{stream})
}

type WorkloadManager_OpenFileServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type workloadManagerOpenFileServer struct {
	grpc.ServerStream
}

func (x *workloadManagerOpenFileServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func _WorkloadManager_TailFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkloadManagerServer).TailFile(m, &workloadManagerTailFileServer{stream})
}

type WorkloadManager_TailFileServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type workloadManagerTailFileServer struct {
	grpc.ServerStream
}

func (x *workloadManagerTailFileServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

var _WorkloadManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WorkloadManager",
	HandlerType: (*WorkloadManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _WorkloadManager_SubmitJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _WorkloadManager_CancelJob_Handler,
		},
		{
			MethodName: "JobInfo",
			Handler:    _WorkloadManager_JobInfo_Handler,
		},
		{
			MethodName: "JobSteps",
			Handler:    _WorkloadManager_JobSteps_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenFile",
			Handler:       _WorkloadManager_OpenFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TailFile",
			Handler:       _WorkloadManager_TailFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/workload/api/workload.proto",
}
